spring.application.name=busbooking

spring.datasource.url=jdbc:mysql://localhost:3306/online_bus_ticket
spring.datasource.username=root
spring.datasource.password=Fiazia@2027

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false